### ISSUE TITLE
No index.html

### ISSUE THREAD

**Issue by boldijar** [DrakeLeung/hexo-theme-again#1]
I do everything I have to do, and after starting the server I get

D:\Projects\Blog\blog>hexo server
INFO  Hexo is running at http://0.0.0.0:4000/. Press Ctrl+C to stop.
WARN  No layout: index.html
WARN  No layout: index.html

**Comment by lyyourc** [comment]
@BoldijarPaul Try to rename the `hexo-theme-again/` as `again/` in the `themes/` directory. It should be same to the value of the `theme` property in the `_config.yml` file. 

Thanks your issue, I gotta update the `README.md`

**Comment by boldijar** [comment]
Yes, it works now, thank you. :+1:
