### ISSUE TITLE
hexo again 

### ISSUE THREAD

**Issue by GeniusLover** [DrakeLeung/hexo-theme-again#11]
How to use Duoshuo Comment？

**Comment by lyyourc** [comment]
You can just google it: [Hexo使用多说教程- 多说开发者中心](http://dev.duoshuo.com/threads/541d3b2b40b5abcd2e4df0e9),
Or check out other themes: [theme list](https://hexo.io/themes/).

Hope can help you 👻

**Comment by GeniusLover** [comment]
thank U. I like your theme,it's very beautifu.

I try to add duoshuo to "again”，but i failed.

Do you use diques?

15868115538@163.com

From: ly你个c
Date: 2016-09-01 17:17
To: DrakeLeung/hexo-theme-again
CC: GenuisLover; Author
Subject: Re: [DrakeLeung/hexo-theme-again] hexo again (#11)
You can just google it: Hexo使用多说教程- 多说开发者中心,
Or check out other themes: theme list.
Hope can help you ????

**Comment by lyyourc** [comment]
Yep, I use [disqus](https://github.com/DrakeLeung/hexo-theme-again/blob/master/layout/_widget/disqus.ejs#L1). So you can add `duoshuo` like that.

**You might missed reading [post.ejs](https://github.com/DrakeLeung/hexo-theme-again/blob/master/layout/post.ejs#L5)** (`theme` variable is read from [config.yml](https://github.com/DrakeLeung/hexo-theme-again/blob/master/_config.yml#L14) )

Or you can push your source code in GitHub and I may can point it out 🙃
