### ISSUE TITLE
help,I can't install this theme!? 

### ISSUE THREAD

**Issue by q27488** [DrakeLeung/hexo-theme-again#16]
as you see:
`
hexo s
**ERROR Plugin load failed: hexo-renderer-sass
Error: %1 is not a valid Win32 application.**
`
what happened? 
the browser display this err: 
http://localhost:4000/css/app.css Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by lyyourc** [comment]
Are you sure that you install the plugin `hexo-renderer-sass`well?

**Comment by opdays** [comment]
朋友 这个主题很好看，但是好像没有文章归档

**Comment by lyyourc** [comment]
@yy584089958 自己搞，丰衣足食。
