### ISSUE TITLE
google_analytics doesn't work

### ISSUE THREAD

**Issue by AymaxLi** [DrakeLeung/hexo-theme-again#17]
## Background
DrakeLeung 大大，i am your 小迷弟 🙊 . when i checked the google analytics of my blog, i found it didn't work.

## Details
Then i read the code of hexo-theme-again to locate the source of this bug. Finally i noticed that there was a spelling mistake in line 36 of `_config.yml` . The property `google_anlytics` should have been `google_analytics` ~

**Comment by lyyourc** [comment]
😂, Pull Request !

**Comment by lyyourc** [comment]
closed #18
