### ISSUE TITLE
手机 CodeBlock 显示bug

### ISSUE THREAD

**Issue by ianhhhhhhhhe** [DrakeLeung/hexo-theme-again#8]
代码部分，行数和代码字体大小不统一，导致首部和尾部行序号处会显示白块。

**Comment by lyyourc** [comment]
什么手机

**Comment by ianhhhhhhhhe** [comment]
我的意思是，在手机端浏览器浏览的时候，字体显示不正常

**Comment by lyyourc** [comment]
什么手机的什么版本的什么浏览器？因为我要重现这个 bug 。

**Comment by ianhhhhhhhhe** [comment]
iPhone 5s, iOS 9.3.2

**Comment by ianhhhhhhhhe** [comment]
safari

**Comment by ianhhhhhhhhe** [comment]
iPhone 5s 的Chrome也出现了这个问题

**Comment by ianhhhhhhhhe** [comment]
不过暂时可以不用管这个问题，因为我发现这个问题是随机出现的，有的文章的code-block会有这个问题，有的就很正常。
